version: '3'
services:
  react-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true