version: '3'
services:
  react-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    volumes: # TO BE USED FOR DEVELOPMENT ONLY
             # NEEDS TO BE UPDATED FOR PRODUCTION
      - ../:/app
      - /app/node_modules
      - static_files:/app/build
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  static_files:
    external: true