version: '3'
services:
  react-frontend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    volumes: # TO BE USED FOR DEVELOPMENT ONLY
             # NEEDS TO BE UPDATED FOR PRODUCTION
      - ../:/app
      - /app/node_modules
      - ../build:/local_build
      - static_files:/volume_build
    command: bash /app/Scripts/startup.sh

    ports:
      - '3000:3000'

volumes:
  static_files:
    external: true